// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9I5ztFuhc_IT2OM4Mx6IkHSzOwJRSh2E',
    appId: '1:634509069834:android:dd74ee7517479e497559f3',
    messagingSenderId: '634509069834',
    projectId: 'majstornaklikapp-5f74c',
    storageBucket: 'majstornaklikapp-5f74c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTKtQWP1YMF3yhhR_eMbLVsGGQujTLkvU',
    appId: '1:634509069834:ios:50d5dc384c63e8207559f3',
    messagingSenderId: '634509069834',
    projectId: 'majstornaklikapp-5f74c',
    storageBucket: 'majstornaklikapp-5f74c.firebasestorage.app',
    iosBundleId: 'com.example.majstorNaKlikApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTKtQWP1YMF3yhhR_eMbLVsGGQujTLkvU',
    appId: '1:634509069834:ios:50d5dc384c63e8207559f3',
    messagingSenderId: '634509069834',
    projectId: 'majstornaklikapp-5f74c',
    storageBucket: 'majstornaklikapp-5f74c.firebasestorage.app',
    iosBundleId: 'com.example.majstorNaKlikApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVTMD7ekahxEBXIfvb-4oycYkXGUfDDIw',
    appId: '1:634509069834:web:22fd50456271269c7559f3',
    messagingSenderId: '634509069834',
    projectId: 'majstornaklikapp-5f74c',
    authDomain: 'majstornaklikapp-5f74c.firebaseapp.com',
    storageBucket: 'majstornaklikapp-5f74c.firebasestorage.app',
  );
}
